### ISSUE TITLE
Tag versions

### ISSUE THREAD

**Issue by joprice** [jdauphant/docker-images#3]
It would be nice to have a tag for each version of archiva, and configure dockerhub to build from those.

**Comment by jdauphant** [comment]
I have created the version 2.2.0 on docker with archiva-2.2.0 associated tags
Thanks for the suggestion

**Comment by joprice** [comment]
Thanks! We've been using my fork at iHeartRadio https://hub.docker.com/r/joprice/archiva/tags/
